// <auto-generated />
using System;
using Asterisk.MyTek.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asterisk.MyTek.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260709072415_Mapping_Table")]
    partial class Mapping_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asterisk.MyTek.Entity.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.ChallengeConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("ChallengeConfigs");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.DevelopmentStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DevelopmentStages");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.MappingChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DevelopmentStageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("DevelopmentStageId");

                    b.ToTable("MappingChallenge");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.ChallengeConfig", b =>
                {
                    b.HasOne("Asterisk.MyTek.Entity.Challenge", "Challenge")
                        .WithMany("ChallengeConfigs")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.MappingChallenge", b =>
                {
                    b.HasOne("Asterisk.MyTek.Entity.Challenge", null)
                        .WithMany("MappingChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asterisk.MyTek.Entity.DevelopmentStage", null)
                        .WithMany("MappingChallenges")
                        .HasForeignKey("DevelopmentStageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.Challenge", b =>
                {
                    b.Navigation("ChallengeConfigs");

                    b.Navigation("MappingChallenges");
                });

            modelBuilder.Entity("Asterisk.MyTek.Entity.DevelopmentStage", b =>
                {
                    b.Navigation("MappingChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
